### ISSUE TITLE
rename speed to acceleration

### ISSUE THREAD

**Issue by ebrahimebrahim** [yusufmte/joustronauts#2]
The variables referred to as "speed" [here](https://github.com/yusufmte/joustronauts/blob/ad08e3506c922bb7b16281f4ce57e4ca641db6ba/lance.gd#L4-L5) are acceleration, considering the way they are used in `RigidBody2D`'s `apply_central_impulse`.

e.g. when you say `export var forward_speed = 2000`, that's not 2000 distance units per second in speed.
There's a gradual speed increase at a rate of 2000 distance/second per second.
A max speed is eventually reached because of the presence of friction.
The max speed is the so called terminal velocity, which you can calculate like as follows.

Let `a0` be the constant acceleration, let `m` be mass, and let `mu` be the friction coefficient. Terminal velocity is reached when the friction force `mu*v` equals the thrust force `m*a0`, so terminal velocity is `m*a/mu`.

In your case `m=1` because mass is not changed and it defaults to 1 for `RigidBody2D`
Currently `a0=2000` and `mu=5`, so the max speed is `1*2000/5=400` distance units per second.

**Comment by ebrahimebrahim** [comment]
Another thought: the max speed is probably what makes more sense to set explicitly, with the acceleration being deduced from that. 

So e.g. instead of 

```gdscript
export var forward_speed = 2000
export var coef_of_friction = 5
```

you can do

```gdscript
export var forward_max_speed = 400
export var coef_of_friction = 5
var forward_thrust = coef_of_friction * forward_max_speed / mass # 2000 in this case; this is what you previously called "forward_speed"
```

(You'd probably want to do one of those `setget` things to make sure `forward_thrust` gets updated properly whenever max speed or friction are modified-- lmk if you are not sure what I mean)

**Comment by yusufmte** [comment]
Peup, TY for this explanation, this is awesome! I actually noticed that and wondered why it was happening-- I had previously had a separate variable for max_speed, which the current velocity would be checked against and the impulse would only be applied if the lance is below max speed. Then, by the time movement was occurring via impulse, I realized it wasn't doing anything (probably because I had set it over 400, in retrospect) and removed it, but wasn't sure what the source of terminal velocity was until now.
