### ISSUE TITLE
use enums instead of string comparison

### ISSUE THREAD

**Issue by ebrahimebrahim** [yusufmte/joustronauts#3]
In `lance.gd`, we see the strings `lance_type` and `name` where an [enum](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#enums) might be more appropriate. Something like this
```gdscript
enum LanceType {PURPLE, ORANGE};
```

Enums work better in game logic, but maybe you went with strings because there are some situations where you want to display the lance type as a string. For that I would recommend a [dict](https://docs.godotengine.org/en/stable/classes/class_dictionary.html) that maps lance type enums to strings that can be displayed.

A similar concept can be applied to getting the "control code" of a lance type. Instead of [setting a control code](https://github.com/yusufmte/joustronauts/blob/ad08e3506c922bb7b16281f4ce57e4ca641db6ba/lance.gd#L17-L22) as a variable that has to stay syncronized to the lance type, the control code can be a dict mapping lance type enum to an "O" or "P".

Also there could be a dict mapping lance type enum to textures, like
```gdscript
var textures = {
  LanceType.PURPLE : purple_sketch,
  LanceType.ORANGE : orange_sketch
}
```

then setting the correct texture becomes simply
```gdscript
$Sprite.texture = textures[lance_type]
```

**Comment by yusufmte** [comment]
Peup, at first I did think the string seemed an odd choice here, but I couldn't remember what the more appropriate choice was-- enum does seem more suitable here!

However, what throws it off is the `name`. When something enters the lance core (as in `_on_Core_body_entered(body)`), the body could be pretty much anything, not necessarily a lance. `name` is a property of the ultimate base class `Node`, so it seemed the safest choice-- every `Node` instance has a name but the orange lance will only react if the body entering is named `"purple_lance"`.

In the last commit I made it a bit less peupy by [getting rid of lance_type and using name alone](https://github.com/yusufmte/joustronauts/blob/main/lance.gd#L13-L17) to eliminate redundancy, and setting the "control code" and Sprite texture based on the provided color. What do you think-- is that better, or is it still peupy because the names of the control code and textures have to be synchronized to the color?

**Comment by ebrahimebrahim** [comment]
> However, what throws it off is the `name`. When something enters the lance core (as in `_on_Core_body_entered(body)`), the body could be pretty much anything, not necessarily a lance. `name` is a property of the ultimate base class `Node`, so it seemed the safest choice-- every `Node` instance has a name but the orange lance will only react if the body entering is named `"purple_lance"`.

You could use the `is` keyword to check that an object is a Lance, [see `is` keyword described here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inheritance).



> In the last commit I made it a bit less peupy by [getting rid of lance_type and using name alone](https://github.com/yusufmte/joustronauts/blob/main/lance.gd#L13-L17) to eliminate redundancy, and setting the "control code" and Sprite texture based on the provided color. What do you think-- is that better, or is it still peupy because the names of the control code and textures have to be synchronized to the color?

It's not necessary to switch to an enum. I agree that b4f760f630829c4f68bc82e888dc6af47975f3aa clears up the issue mostly. But I guess having a lance type enum would more clearly communicate your intent in the code, and make errors messages more understandable if the same code were misused later. (E.g. think about what happens if I try to create a new lance type and forget certain aspects of it, things like that.) Up to you.

**Comment by yusufmte** [comment]
Peup, ty, the `is` keyword is exactly what I need here! I would feel better about using an enum for sure, I'd rather start out with more clear practices so it doesn't create problems down the line.

**Comment by yusufmte** [comment]
Can't use the `if body is Lance` in lance.gd, as I get this error due to referring to Lance within its own definition:

`Parser Error: Using own name in class file is not allowed (creates a cyclic reference)`

Trying to figure out a smooth way to figure out if the body is a Lance...Maybe this means this function doesn't belong in Lance?

**Comment by ebrahimebrahim** [comment]
Looking at 9a81cef9cb7147fa425eaa74d706322c2fd2dc3a, does lance type really have to be global? Does it not work to do it in `lance.gd`?


---

> Can't use the `if body is Lance` in lance.gd, as I get this error due to referring to Lance within its own definition:

Hmm, and the [discussion here](https://www.reddit.com/r/godot/comments/gjt91q/comment/fqoeyqf/?utm_source=share&utm_medium=web2x&context=3) is not promising.
I guess this is getting more complicated than it's worth. Maybe checking the collider name is the best solution for now.

**Comment by ebrahimebrahim** [comment]
[Check this out](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/static_typing.html#variable-casting)
Does it work to use the `as` keyword and check for `null` as in that example?

**Comment by yusufmte** [comment]
> Looking at https://github.com/yusufmte/joustronauts/commit/9a81cef9cb7147fa425eaa74d706322c2fd2dc3a, does lance type really have to be global? Does it not work to do it in lance.gd?

It does feel odd to make a global script just for that (though it might be used for other things later), but the reason for it is so that `joust.gd` can use the `LanceType` enum too, when summoning the lances so it can tell them what type to be. Is that peupy?

> Hmm, and the [discussion here](https://www.reddit.com/r/godot/comments/gjt91q/comment/fqoeyqf/?utm_source=share&utm_medium=web2x&context=3) is not promising.

Doing it with `get_script()` to identify the current class is actually working!! It looks like there were bugs with `get_script()` earlier based on that discussion, but it's from 2 yr ago and 0.2 godot versions ago -- peurhaps it's been fixed since then?

But it's great to know about the `as` keyword and that I can do typecasting in GDScript!

peup.
